@startuml
!theme plain
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle

package "iam.domain.model" #F4F6F6 {
  class SignIn {
    - _id: number
    - _email: string
    - _password: string
  }
  class SignUp {
    - _id: number
    - _firstName: string
    - _lastName: string
    - _email: string
    - _password: string
    - _rol: 'administrator' | 'family'
  }
}

package "iam.application" #F4F6F6 {
  class IamStore {
    - _signInSignal: Signal<SignIn>
    - _loadingSignal: Signal<boolean>
    - _errorSignal: Signal<string>
    - iamApi: IamApi
    + signIn: Signal<SignIn>
    + loading: Signal<boolean>
    + error: Signal<string>
    + createSignIn(signIn: SignIn)
    + createSignUp(signUp: SignUp)
  }
}

package "iam.infrastructure" #F4F6F6 {
  class IamApi {
    - _signInApiEndpoint: SignInApiEndpoint
    - _signUpApiEndpoint: SignUpApiEndpoint
    + createSignIn(signIn: SignIn): Observable<SignIn>
    + createSignUp(signUp: SignUp): Observable<SignUp>
  }
  class SignInApiEndpoint {
    - assembler: SignInAssembler
    + login(signIn: SignIn): Observable<SignIn>
  }
  class SignUpApiEndpoint {
    - assembler: SignUpAssembler
    + register(signUp: SignUp): Observable<SignUp>
  }
  class SignInAssembler {
    + toEntityFromResource(res: SignInResource): SignIn
    + toResourceFromEntity(ent: SignIn): SignInResource
  }
  class SignUpAssembler {
    + toEntityFromResource(res: SignUpResource): SignUp
    + toResourceFromEntity(ent: SignUp): SignUpResource
  }
  interface SignInResource {
    id: number
    email: string
    password: string
  }
  interface SignUpResource {
    id: number
    firstName: string
    lastName: string
    email: string
    password: string
    role: 'administrator' | 'family'
  }
}

package "iam.presentation" #F4F6F6 {
  object IamRouters {
    routes: Routes
  }

  package "components" {
    class AuthenticationSection <<component>> {
      - router: Router
      + onRegisterAdmin()
      + onRegisterFamily()
    }
  }
  package "views" {
    class SignInComponent <<component>> {
      form: FormGroup
      iamStore: IamStore
      + onSubmit()
    }
    class SignUpComponent <<component>> {
      form: FormGroup
      iamStore: IamStore
      userRole: 'administrator' | 'family'
      - route: ActivatedRoute
      + onSubmit()
    }
  }
}

' --- Relationships ---

' Presentation Layer
SignInComponent --> IamStore : "uses"
SignInComponent --> SignIn : "creates"
SignUpComponent --> IamStore : "uses"
SignUpComponent --> SignUp : "creates"
AuthenticationSection ..> IamRouters : "triggers navigation defined in"

' Routing
IamRouters ..> SignInComponent : "lazy loads"
IamRouters ..> SignUpComponent : "lazy loads"


' Application Layer
IamStore --> IamApi : "uses"
IamStore ..> SignIn : "manages state of"
IamStore ..> SignUp : "manages state of"


' Infrastructure Layer
IamApi --> SignInApiEndpoint : "delegates to"
IamApi --> SignUpApiEndpoint : "delegates to"
SignInApiEndpoint --> SignInAssembler : "uses"
SignUpApiEndpoint --> SignUpAssembler : "uses"

' Assemblers
SignInAssembler --> SignIn : "creates"
SignInAssembler ..> SignInResource : "transforms"
SignUpAssembler --> SignUp : "creates"
SignUpAssembler ..> SignUpResource : "transforms"
@enduml
